In [15]:
import sympy
from sympy import S
from sympy.physics.wigner import wigner_3j
from sympy.physics.wigner import wigner_6j
import numpy as np
import scipy.constants as sc


##now add hyperfine 

s = S(1)/2; I = S(1)/2
f1 = 1; j1 = S(1)/2; l1 = 0
f2 = 0; j2 = S(1)/2; l2 = 1

H00 = np.zeros([(2*f1+1),(2*f2+1)])

for i in range(-f1,f1+1):
    for j in range(1):
        c1 = wigner_3j(f1, 1, f2, i, -i+j , -j)*(-1)**(f1-i)
        c2 = wigner_6j(j1,f1,S(1)/2,f2,j2,1)*sympy.sqrt(2*f1+1)*sympy.sqrt(2*f2+1)*(-1)**(j1+I+f2+1)
        c3 = wigner_6j(l1,j1,S(1)/2,j2,l2,1)*sympy.sqrt(2*j1+1)*sympy.sqrt(2*j2+1)*(-1)**(j1+I+f2+1)
        H00[i+1,j] = c1*c2*c3
            
print(H00)

s = S(1)/2; I = S(1)/2
f2 = 1; j2 = S(1)/2; l2 = 1

H01 = np.zeros([(2*f1+1),(2*f2+1)])

for i in range(-f1,f1+1):
    for j in range(-f2,f2+1):
        c1 = wigner_3j(f1, 1, f2, i, -i+j , -j)*(-1)**(f1-i)
        c2 = wigner_6j(j1,f1,S(1)/2,f2,j2,1)*sympy.sqrt(2*f1+1)*sympy.sqrt(2*f2+1)*(-1)**(j1+I+f2+1)
        c3 = wigner_6j(l1,j1,S(1)/2,j2,l2,1)*sympy.sqrt(2*j1+1)*sympy.sqrt(2*j2+1)*(-1)**(j1+I+f2+1)
        H01[i+1,j+1] = c1*c2*c3
            
print(H01)


s = S(1)/2; I = S(1)/2
f2 = 1; j2 = S(3)/2; l2 = 1

H02 = np.zeros([(2*f1+1),(2*f2+1)])

for i in range(-f1,f1+1):
    for j in range(-f2,f2+1):
        c1 = wigner_3j(f1, 1, f2, i, -i+j , -j)*(-1)**(f1-i)
        c2 = wigner_6j(j1,f1,S(1)/2,f2,j2,1)*sympy.sqrt(2*f1+1)*sympy.sqrt(2*f2+1)*(-1)**(j1+I+f2+1)
        c3 = wigner_6j(l1,j1,S(1)/2,j2,l2,1)*sympy.sqrt(2*j1+1)*sympy.sqrt(2*j2+1)*(-1)**(j1+I+f2+1)
        H02[i+1,j+1] = c1*c2*c3
            
print(H02)

s = S(1)/2; I = S(1)/2
f2 = 2; j2 = S(3)/2; l2 = 1
H03 = np.zeros([(2*f1+1),(2*f2+1)])

for i in range(-f1,f1+1):
    for j in range(-f2,f2+1):
        c1 = wigner_3j(f1, 1, f2, i, -i+j , -j)*(-1)**(f1-i)
        c2 = wigner_6j(j1,f1,S(1)/2,f2,j2,1)*sympy.sqrt(2*f1+1)*sympy.sqrt(2*f2+1)*(-1)**(j1+I+f2+1)
        c3 = wigner_6j(l1,j1,S(1)/2,j2,l2,1)*sympy.sqrt(2*j1+1)*sympy.sqrt(2*j2+1)*(-1)**(j1+I+f2+1)
        H03[i+1,j+f2] = c1*c2*c3
            
print(H03)


htot = 0
for i in range(len(H00[0])):
    htot += H00[0,i]**2
for i in range(len(H01[0])):
    htot += H01[0,i]**2 
for i in range(len(H02[0])):
    htot += H02[0,i]**2
for i in range(len(H03[0])):
    htot += H03[0,i]**2
htot


[[0.33333333]
 [0.33333333]
 [0.33333333]]
[[-0.33333333  0.33333333  0.        ]
 [-0.33333333  0.          0.33333333]
 [ 0.         -0.33333333  0.33333333]]
[[ 0.23570226 -0.23570226  0.        ]
 [ 0.23570226  0.         -0.23570226]
 [ 0.          0.23570226 -0.23570226]]
[[-0.57735027  0.40824829 -0.23570226  0.          0.        ]
 [ 0.         -0.40824829  0.47140452 -0.40824829  0.        ]
 [ 0.          0.         -0.23570226  0.40824829 -0.57735027]]


0.9999999999999999

In [24]:
import sympy
from sympy import S
from sympy.physics.wigner import wigner_3j
from sympy.physics.wigner import wigner_6j
import numpy as np
import scipy.constants as sc


##now add hyperfine 

s = S(1)/2; I = S(1)/2
f1 = 3; j1 = S(5)/2; l1 = 2


s = S(1)/2; I = S(1)/2
f2 = 2; j2 = S(3)/2; l2 = 1

H01 = np.zeros([(2*f1+1),(2*f2+1)])

for i in range(-f1,f1+1):
    for j in range(-f2,f2+1):
        c1 = wigner_3j(f1, 1, f2, i, -i+j , -j)*(-1)**(f1-i)
        c2 = wigner_6j(j1,f1,S(1)/2,f2,j2,1)*sympy.sqrt(2*f1+1)*sympy.sqrt(2*f2+1)*(-1)**(j1+I+f2+1)
        c3 = wigner_6j(l1,j1,S(1)/2,j2,l2,1)*sympy.sqrt(2*j1+1)*sympy.sqrt(2*j2+1)*(-1)**(j1+I+f2+1)
        H01[i+f1,j+f2] = c1*c2*c3
            
print(H01)


s = S(1)/2; I = S(1)/2
f2 = 1; j2 = S(3)/2; l2 = 1

H02 = np.zeros([(2*f1+1),(2*f2+1)])

for i in range(-f1,f1+1):
    for j in range(-f2,f2+1):
        c1 = wigner_3j(f1, 1, f2, i, -i+j , -j)*(-1)**(f1-i)
        c2 = wigner_6j(j1,f1,S(1)/2,f2,j2,1)*sympy.sqrt(2*f1+1)*sympy.sqrt(2*f2+1)*(-1)**(j1+I+f2+1)
        c3 = wigner_6j(l1,j1,S(1)/2,j2,l2,1)*sympy.sqrt(2*j1+1)*sympy.sqrt(2*j2+1)*(-1)**(j1+I+f2+1)
        H02[i+f1,j+f2] = c1*c2*c3
            
print(H02)




htot = 0

for i in range(len(H01[0])):
    htot += (H01[2,i]*np.sqrt(5))**2 
for i in range(len(H02[0])):
    htot += H02[2,i]**2

htot


[[-0.4472136   0.          0.          0.          0.        ]
 [-0.25819889 -0.36514837  0.          0.          0.        ]
 [-0.11547005 -0.32659863 -0.28284271  0.          0.        ]
 [ 0.         -0.2        -0.34641016 -0.2         0.        ]
 [ 0.          0.         -0.28284271 -0.32659863 -0.11547005]
 [ 0.          0.          0.         -0.36514837 -0.25819889]
 [ 0.          0.          0.          0.         -0.4472136 ]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


1.0

In [33]:
import sympy
from sympy import S
from sympy.physics.wigner import wigner_3j
from sympy.physics.wigner import wigner_6j
import numpy as np
import scipy.constants as sc


##now add hyperfine 

s = S(1)/2; I = S(1)/2
f1 = 2; j1 = S(5)/2; l1 = 2
f2 = 1; j2 = S(3)/2; l2 = 1

H00 = np.zeros([(2*f1+1),(2*f2+1)])

for i in range(-f1,f1+1):
    for j in range(-f2,f2+1):
        c1 = wigner_3j(f1, 1, f2, i, -i+j , -j)*(-1)**(f1-i)
        c2 = wigner_6j(j1,f1,S(1)/2,f2,j2,1)*sympy.sqrt(2*f1+1)*sympy.sqrt(2*f2+1)*(-1)**(j1+I+f2+1)
        c3 = wigner_6j(l1,j1,S(1)/2,j2,l2,1)*sympy.sqrt(2*j1+1)*sympy.sqrt(2*j2+1)*(-1)**(j1+I+f2+1)
        H00[i+1,j] = c1*c2*c3
            
print(H00)

s = S(1)/2; I = S(1)/2
f2 = 2; j2 = S(3)/2; l2 = 1

H01 = np.zeros([(2*f1+1),(2*f2+1)])

for i in range(-f1,f1+1):
    for j in range(-f2,f2+1):
        c1 = wigner_3j(f1, 1, f2, i, -i+j , -j)*(-1)**(f1-i)
        c2 = wigner_6j(j1,f1,S(1)/2,f2,j2,1)*sympy.sqrt(2*f1+1)*sympy.sqrt(2*f2+1)*(-1)**(j1+I+f2+1)
        c3 = wigner_6j(l1,j1,S(1)/2,j2,l2,1)*sympy.sqrt(2*j1+1)*sympy.sqrt(2*j2+1)*(-1)**(j1+I+f2+1)
        H01[i+1,j+1] = c1*c2*c3
            
print(H01)







htot = 0
for i in range(len(H00[0])):
    htot += (H00[4,i]*np.sqrt(5))**2 
for i in range(len(H01[0])):
    htot += (H01[4,i]*np.sqrt(5))**2 

htot


[[0.3        0.         0.3       ]
 [0.34641016 0.17320508 0.17320508]
 [0.3        0.3        0.        ]
 [0.         0.42426407 0.        ]
 [0.         0.         0.42426407]]
[[ 0.05773503 -0.1         0.          0.          0.08164966]
 [ 0.1         0.         -0.1         0.          0.        ]
 [ 0.          0.1        -0.05773503 -0.08164966  0.        ]
 [ 0.          0.          0.08164966 -0.11547005  0.        ]
 [-0.08164966  0.          0.          0.          0.11547005]]


1.0000000000000002

In [36]:
import sympy
from sympy import S
from sympy.physics.wigner import wigner_3j
from sympy.physics.wigner import wigner_6j
import numpy as np
import scipy.constants as sc


##now add hyperfine 

s = S(1)/2; I = S(1)/2
f1 = 2; j1 = S(3)/2; l1 = 2
f2 = 0; j2 = S(1)/2; l2 = 1

H00 = np.zeros([(2*f1+1),(2*f2+1)])

for i in range(-f1,f1+1):
    for j in range(1):
        c1 = wigner_3j(f1, 1, f2, i, -i+j , -j)*(-1)**(f1-i)
        c2 = wigner_6j(j1,f1,S(1)/2,f2,j2,1)*sympy.sqrt(2*f1+1)*sympy.sqrt(2*f2+1)*(-1)**(j1+I+f2+1)
        c3 = wigner_6j(l1,j1,S(1)/2,j2,l2,1)*sympy.sqrt(2*j1+1)*sympy.sqrt(2*j2+1)*(-1)**(j1+I+f2+1)
        H00[i+1,j] = c1*c2*c3
            
print(H00)

s = S(1)/2; I = S(1)/2
f2 = 1; j2 = S(1)/2; l2 = 1

H01 = np.zeros([(2*f1+1),(2*f2+1)])

for i in range(-f1,f1+1):
    for j in range(-f2,f2+1):
        c1 = wigner_3j(f1, 1, f2, i, -i+j , -j)*(-1)**(f1-i)
        c2 = wigner_6j(j1,f1,S(1)/2,f2,j2,1)*sympy.sqrt(2*f1+1)*sympy.sqrt(2*f2+1)*(-1)**(j1+I+f2+1)
        c3 = wigner_6j(l1,j1,S(1)/2,j2,l2,1)*sympy.sqrt(2*j1+1)*sympy.sqrt(2*j2+1)*(-1)**(j1+I+f2+1)
        H01[i+1,j+1] = c1*c2*c3
            
print(H01)


s = S(1)/2; I = S(1)/2
f2 = 1; j2 = S(3)/2; l2 = 1

H02 = np.zeros([(2*f1+1),(2*f2+1)])

for i in range(-f1,f1+1):
    for j in range(-f2,f2+1):
        c1 = wigner_3j(f1, 1, f2, i, -i+j , -j)*(-1)**(f1-i)
        c2 = wigner_6j(j1,f1,S(1)/2,f2,j2,1)*sympy.sqrt(2*f1+1)*sympy.sqrt(2*f2+1)*(-1)**(j1+I+f2+1)
        c3 = wigner_6j(l1,j1,S(1)/2,j2,l2,1)*sympy.sqrt(2*j1+1)*sympy.sqrt(2*j2+1)*(-1)**(j1+I+f2+1)
        H02[i+1,j+1] = c1*c2*c3
            
print(H02)

s = S(1)/2; I = S(1)/2
f2 = 2; j2 = S(3)/2; l2 = 1
H03 = np.zeros([(2*f1+1),(2*f2+1)])

for i in range(-f1,f1+1):
    for j in range(-f2,f2+1):
        c1 = wigner_3j(f1, 1, f2, i, -i+j , -j)*(-1)**(f1-i)
        c2 = wigner_6j(j1,f1,S(1)/2,f2,j2,1)*sympy.sqrt(2*f1+1)*sympy.sqrt(2*f2+1)*(-1)**(j1+I+f2+1)
        c3 = wigner_6j(l1,j1,S(1)/2,j2,l2,1)*sympy.sqrt(2*j1+1)*sympy.sqrt(2*j2+1)*(-1)**(j1+I+f2+1)
        H03[i+1,j+f2] = c1*c2*c3
            
print(H03)


htot = 0
for i in range(len(H00[0])):
    htot += H00[0,i]**2
for i in range(len(H01[0])):
    htot += H01[0,i]**2 
for i in range(len(H02[0])):
    htot += H02[0,i]**2
for i in range(len(H03[0])):
    htot += H03[0,i]**2
htot


[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[0.28867513 0.28867513 0.        ]
 [0.16666667 0.33333333 0.16666667]
 [0.         0.28867513 0.28867513]
 [0.         0.         0.40824829]
 [0.40824829 0.         0.        ]]
[[0.04082483 0.04082483 0.        ]
 [0.02357023 0.04714045 0.02357023]
 [0.         0.04082483 0.04082483]
 [0.         0.         0.05773503]
 [0.05773503 0.         0.        ]]
[[-0.1        -0.07071068  0.12247449  0.          0.        ]
 [ 0.         -0.12247449  0.          0.12247449  0.        ]
 [ 0.          0.         -0.12247449  0.07071068  0.1       ]
 [ 0.          0.          0.         -0.1         0.14142136]
 [-0.14142136  0.1         0.          0.          0.        ]]


0.2