## Wigner Eckhart Theorem

$$
<n',j',m'|T^k_q|n,j,m> = <j',m'|k,q;j,m> \cdot \frac{<n',j'||T^k||n,j>}{\sqrt{2j'+1}}
$$
equivalently 
$$
<n',j',m'|T^k_q|n,j,m> = \\
\begin{pmatrix} 
j' & k & j \\
-m' & q & m 
\end{pmatrix} \cdot <n',j'||T^k||n,j> (-1)^{j'-m'}
$$

Spectator theorem for hyperfine
$$
<n', F', mf' |T^k_q| n, F, mf> =  \\
\begin{pmatrix} 
F' & k & F \\
-m_F' & q & m_F 
\end{pmatrix} 
\cdot (-1)^{F'-m_F'} \cdot \sqrt{2F'+1} \sqrt{2F +1} \cdot 
\begin{Bmatrix} 
J' & F' & I \\
F & J & k 
\end{Bmatrix}\\
\cdot (-1)^{J'+I+J+1} 
\cdot \sqrt{2J'+1} \sqrt{2J +1} \cdot 
\begin{Bmatrix} 
L' & J' & S \\
J & L & k 
\end{Bmatrix}\cdot (-1)^{L'+S+J+1} \cdot <n',l'||T^k||n,l>
$$

In [2]:
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.ticker import MultipleLocator, FormatStrFormatter
import math
import cmath
import scipy.constants as sc
import time
%matplotlib inline
import sympy

####input to function is j_1,j_2,j_3,m_1,m_2,m_3
from sympy import S
from sympy.physics.wigner import clebsch_gordan
print(clebsch_gordan(S(3)/2, S(1)/2, 2, S(3)/2, S(1)/2, 2))

from sympy.physics.wigner import wigner_3j
print(wigner_3j(2, 6, 4, 0, 0, 0))


from sympy.physics.wigner import wigner_6j
print(wigner_6j(3,3,3,3,3,3))


from sympy.physics.wigner import wigner_9j
x = wigner_9j(1,1,1, 1,1,1, 1,1,0) 

print(clebsch_gordan(S(3)/2, S(1)/2, 2, S(3)/2, S(1)/2, 2))
print(wigner_3j(S(3)/2, S(1)/2, 2, S(3)/2, S(1)/2, -2)*(sympy.sqrt(2*2+1)*(-1)**(-S(3)/2+S(1)/2-2)))

1
sqrt(715)/143
-1/14
1
1


## Example
$$
<l'=1, s=\frac{1}{2}, j' = \frac{3}{2}, m_j' = \frac{1}{2} |r_q| l=2, s=\frac{1}{2}, j = \frac{3}{2}, m_j = \frac{1}{2}>$$

In [3]:
from sympy import *

###First do long way##
cbi_sd = clebsch_gordan(2, S(1)/2, S(3)/2, 1, S(-1)/2, S(1)/2)
cbi_su = clebsch_gordan(2, S(1)/2, S(3)/2, 0, S(1)/2, S(1)/2)

cbf_sd = clebsch_gordan(1, S(1)/2, S(3)/2, 1, S(-1)/2, S(1)/2)
cbf_su = clebsch_gordan(1, S(1)/2, S(3)/2, 0, S(1)/2, S(1)/2)

cby1 = clebsch_gordan(2, 1, 1, 1, 0, 1)
cby2 = clebsch_gordan(2, 1, 1, 0, 0, 0)

(cbi_sd*cbf_sd*cby1+cbi_su*cbf_su*cby2)*S(1)/sympy.sqrt(2+1)


sqrt(2)/30

In [4]:
from sympy.physics.wigner import wigner_6j
import sympy
##Using the 'spectator theorem from Doyle notes'
wigner_6j(2,S(3)/2,S(1)/2,S(3)/2,1,1)*wigner_3j(S(3)/2,1, S(3)/2, -S(1)/2, 0, S(1)/2)*sympy.sqrt(2*S(3)/2+1)*sympy.sqrt(2*S(3)/2+1)*(-1)


sqrt(2)/30

## Example
Generate all the coupling coefficients between the s and p orbitals including spin, store in matrix with row = final state mj
col  = initial state mj

In [5]:
l1 = 0
l2 = 1
H = np.zeros([2*(2*l2+1),2*(2*l1+1)])

for i in range(2*(2*l1+1)):
    for j in range(2*(2*l2+1)):
        if j < 2:
            H[j,i] = wigner_6j(1,S(1)/2,S(1)/2,S(1)/2,0,1)*wigner_3j(S(1)/2, 1, S(1)/2, (-1)**(i+1)*(j-S(1)/2), j*(-1)**i, i-S(1)/2)*sympy.sqrt(2*S(1)/2+1)*sympy.sqrt(2*S(1)/2+1)
        if j >= 2:
            H[j,i] = wigner_6j(1,S(3)/2,S(1)/2,S(1)/2,0,1)*wigner_3j(S(3)/2, 1, S(1)/2, (-1)**(i+1)*(j-3-S(1)/2), (j-3)*(-1)**i, i-S(1)/2)*sympy.sqrt(2*S(3)/2+1)*sympy.sqrt(2*S(1)/2+1)


            
print(H)

[[ 0.33333333  0.33333333]
 [-0.47140452 -0.47140452]
 [ 0.57735027 -0.57735027]
 [-0.47140452  0.47140452]
 [ 0.33333333 -0.33333333]
 [ 0.          0.        ]]


In [6]:
htot = 0
for i in range(2*(2*l1+1)):
    for j in range(2*(2*l2+1)):
        htot += H[j,i]**2
    
htot

htot = 0
for i in range(2*(2*l1+1)):
    for j in range(2*(2*l2+1)):
        htot += H[j,i]**2
    
htot


htot = 0
for j in range(2*(2*l2+1)):
        htot += H[j,1]**2
    
htot

1.0

In [7]:
##now add hyperfine 

s = S(1)/2; I = S(1)/2
f1 = 0; j1 = S(1)/2; l1 = 0
f2 = 0; j2 = S(1)/2; l2 = 1

H00 = np.zeros([(2*f1+1),(2*f2+1)])

for i in range(2*f1+1):
    for j in range(1):
        c1 = wigner_3j(f1, 1, f2, i, i+j , -j)*(-1)**(f1-i)
        c2 = wigner_6j(j1,f1,S(1)/2,f2,j2,1)*sympy.sqrt(2*f1+1)*sympy.sqrt(2*f2+1)*(-1)**(j1+I+f2+1)
        c3 = wigner_6j(l1,j1,S(1)/2,j2,l2,1)*sympy.sqrt(2*j1+1)*sympy.sqrt(2*j2+1)*(-1)**(j1+I+f2+1)
        H00[i,j] = c1*c2*c3
            
print(H00)

s = S(1)/2; I = S(1)/2
f1 = 0; j1 = S(1)/2; l1 = 0
f2 = 1; j2 = S(1)/2; l2 = 1

H01 = np.zeros([(2*f1+1),(2*f2+1)])

for i in range(2*f1+1):
    for j in range(-f2,f2+1):
        c1 = wigner_3j(f1, 1, f2, i, i+j , -j)*(-1)**(f1-i)
        c2 = wigner_6j(j1,f1,S(1)/2,f2,j2,1)*sympy.sqrt(2*f1+1)*sympy.sqrt(2*f2+1)*(-1)**(j1+I+f2+1)
        c3 = wigner_6j(l1,j1,S(1)/2,j2,l2,1)*sympy.sqrt(2*j1+1)*sympy.sqrt(2*j2+1)*(-1)**(j1+I+f2+1)
        H01[i,j] = c1*c2*c3
            
print(H01)


s = S(1)/2; I = S(1)/2
f1 = 0; j1 = S(1)/2; l1 = 0
f2 = 1; j2 = S(3)/2; l2 = 1

H02 = np.zeros([(2*f1+1),(2*f2+1)])

for i in range(2*f1+1):
    for j in range(-f2,f2+1):
        c1 = wigner_3j(f1, 1, f2, i, i+j , -j)*(-1)**(f1-i)
        c2 = wigner_6j(j1,f1,S(1)/2,f2,j2,1)*sympy.sqrt(2*f1+1)*sympy.sqrt(2*f2+1)*(-1)**(j1+I+f2+1)
        c3 = wigner_6j(l1,j1,S(1)/2,j2,l2,1)*sympy.sqrt(2*j1+1)*sympy.sqrt(2*j2+1)*(-1)**(j1+I+f2+1)
        H02[i,j] = c1*c2*c3
            
print(H02)

s = S(1)/2; I = S(1)/2
f1 = 0; j1 = S(1)/2; l1 = 0
f2 = 2; j2 = S(3)/2; l2 = 1
H03 = np.zeros([(2*f1+1),(2*f2+1)])

for i in range(2*f1+1):
    for j in range(-f2,f2+1):
        c1 = wigner_3j(f1, 1, f2, i, i+j , -j)*(-1)**(f1-i)
        c2 = wigner_6j(j1,f1,S(1)/2,f2,j2,1)*sympy.sqrt(2*f1+1)*sympy.sqrt(2*f2+1)*(-1)**(j1+I+f2+1)
        c3 = wigner_6j(l1,j1,S(1)/2,j2,l2,1)*sympy.sqrt(2*j1+1)*sympy.sqrt(2*j2+1)*(-1)**(j1+I+f2+1)
        H03[i,j] = c1*c2*c3
            
print(H03)


htot = 0
for i in range(len(H00[0])):
    htot += H00[0,i]**2
for i in range(len(H01[0])):
    htot += H01[0,i]**2 
for i in range(len(H02[0])):
    htot += H02[0,i]**2
for i in range(len(H03[0])):
    htot += H03[0,i]**2
htot


[[0.]]
[[-0.33333333  0.33333333  0.33333333]]
[[-0.47140452  0.47140452  0.47140452]]
[[0. 0. 0. 0. 0.]]


1.0

## Example
$$
<I'=\frac{1}{2}, J'=\frac{1}{2}, F' = 0, m_F' = 0 |r_q| I=\frac{1}{2}, J=\frac{1}{2}, F = 1, m_F = 0 >$$

In [8]:
Iui = clebsch_gordan(S(1)/2,S(1)/2,1,-S(1)/2,S(1)/2,0)
Idi = clebsch_gordan(S(1)/2,S(1)/2,1,S(1)/2,-S(1)/2,0)

Sdi = clebsch_gordan(0,S(1)/2,S(1)/2,0,-S(1)/2,-S(1)/2)
Sui = clebsch_gordan(0,S(1)/2,S(1)/2,0,S(1)/2,S(1)/2)

Iuf = clebsch_gordan(S(1)/2,S(1)/2,0,-S(1)/2,S(1)/2,0)
Idf = clebsch_gordan(S(1)/2,S(1)/2,0,S(1)/2,-S(1)/2,0)

Sdf = clebsch_gordan(1,S(1)/2,S(1)/2,0,-S(1)/2,-S(1)/2)
Suf = clebsch_gordan(1,S(1)/2,S(1)/2,0,S(1)/2,S(1)/2)

cg1 = wigner_3j(0,1,1,0,0,0)

cg1*(Iui*Sdi*Iuf*Sdf+Idi*Sui*Idf*Suf)



1/3

In [25]:
s = S(1)/2
I = S(1)/2


f1 = 1
mf1 = -1
j1 = S(1)/2
l1 = 1


f2 = 0
mf2 = 0
j2 = S(1)/2
l2 = 0


q = -1

c1 = wigner_3j(f1, 1, f2, -mf1, q , mf2)*(-1)**(f1-mf1)
c2 = wigner_6j(j1,f1,S(1)/2,f2,j2,1)*sympy.sqrt(2*f1+1)*sympy.sqrt(2*f2+1)*(-1)**(j1+I+f2+1)
c3 = wigner_6j(l1,j1,S(1)/2,j2,l2,1)*sympy.sqrt(2*j1+1)*sympy.sqrt(2*j2+1)*(-1)**(j1+I+f2+1)

c1*c2*c3 
c1

sqrt(3)/3

In [10]:
s = S(1)/2
I = S(1)/2


f1 = 1
mf1 = 1
j1 = S(1)/2
l1 = 1


f2 = 1
mf2 = 0
j2 = S(1)/2
l2 = 0



q = -1



Iui = clebsch_gordan(S(1)/2,j1,f1,S(1)/2,mf1-S(1)/2,mf1)
Idi = clebsch_gordan(S(1)/2,j1,f1,-S(1)/2,mf1+S(1)/2,mf1)

Iuf = clebsch_gordan(S(1)/2,j2,f2,S(1)/2,mf2-S(1)/2,mf2)
Idf = clebsch_gordan(S(1)/2,j2,f2,-S(1)/2,mf2+S(1)/2,mf2)

cg1 = clebsch_gordan(j1,1,j2,mf1-S(1)/2,q, mf2-S(1)/2)
cg2 = clebsch_gordan(j1,1,j2,mf1+S(1)/2,q, mf2+S(1)/2)

(cg1*(Iui*Iuf)+cg2*(Idi*Idf))/sympy.sqrt(2*j1+1)

sqrt(6)/6

In [11]:
f1 = 1
mf1 = 0
j1 = S(1)/2
l1 = 0


f2 = 1
mf2 = 1
j2 = S(1)/2
l2 = 1

s = S(1)/2
I = S(1)/2


q = 1



Iui = clebsch_gordan(S(1)/2,j1,f1,S(1)/2,mf1-S(1)/2,mf1)
Idi = clebsch_gordan(S(1)/2,j1,f1,-S(1)/2,mf1+S(1)/2,mf1)

Iuf = clebsch_gordan(S(1)/2,j2,f2,S(1)/2,mf2-S(1)/2,mf2)
Idf = clebsch_gordan(S(1)/2,j2,f2,-S(1)/2,mf2+S(1)/2,mf2)

cg1 = clebsch_gordan(j1,1,j2,mf1-S(1)/2,q, mf2-S(1)/2)
cg2 = clebsch_gordan(j1,1,j2,mf1+S(1)/2,q, mf2+S(1)/2)

(cg1*(Iui*Iuf)+cg2*(Idi*Idf))/sympy.sqrt(2*j2+1)

-sqrt(6)/6

In [12]:
s = S(1)/2
I = S(1)/2


f1 = 1
mf1 = -1
j1 = S(1)/2
l1 = 1


f2 = 1
mf2 = 0
j2 = S(1)/2
l2 = 0



q = -1

c1 = wigner_3j(f1, 1, f2, -mf1, q , mf2)*(-1)**(f1-mf1)
c2 = wigner_6j(j1,j2,1,f1,f2,S(1)/2)*sympy.sqrt(2*f1+1)*sympy.sqrt(2*f2+1)*sympy.sqrt(2*j1+1)*(-1)**(j1+I+f2+1)


c1*c2

sqrt(3)/3

In [13]:
s = S(1)/2
I = S(1)/2



f1 = 1
mf1 = 0
j1 = S(1)/2
l1 = 0


f2 = 1
mf2 = 1
j2 = S(1)/2
l2 = 1

q = -1


c1 = wigner_3j(f1, 1, f2, -mf1, q , mf2)*(-1)**(f1-mf1)
c2 = wigner_6j(j1,f1,S(1)/2,f2,j2,1)*sympy.sqrt(2*f1+1)*sympy.sqrt(2*f2+1)*(-1)**(j1+I+f2+1)

c1*c2

sqrt(6)/6

In [14]:
clebsch_gordan(2,1,1,0,0,0)/(sympy.sqrt(3))

-sqrt(30)/15

In [15]:
clebsch_gordan(1,1,2,0,0,0)/(sympy.sqrt(5))

sqrt(30)/15

In [16]:
wigner_6j(j1,j2,1,f1,f2,S(1)/2)

-1/3

In [17]:
wigner_6j(j1,f1,S(1)/2,f2,j2,1)

-1/3